/* Generated By:JJTree: Do not edit this line. Node.java */
/*
* The Apache Software License, Version 1.1
*
* Copyright (c) 2000-2001 The Apache Software Foundation.  All rights
* reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions
* are met:
*
* 1. Redistributions of source code must retain the above copyright
*    notice, this list of conditions and the following disclaimer.
*
* 2. Redistributions in binary form must reproduce the above copyright
*    notice, this list of conditions and the following disclaimer in
*    the documentation and/or other materials provided with the
*    distribution.
*
* 3. The end-user documentation included with the redistribution, if
*    any, must include the following acknowlegement:
*       "This product includes software developed by the
*        Apache Software Foundation (http://www.apache.org/)."
*    Alternately, this acknowlegement may appear in the software itself,
*    if and wherever such third-party acknowlegements normally appear.
*
* 4. The names "The Jakarta Project", "Velocity", and "Apache Software
*    Foundation" must not be used to endorse or promote products derived
*    from this software without prior written permission. For written
*    permission, please contact apache@apache.org.
*
* 5. Products derived from this software may not be called "Apache"
*    nor may "Apache" appear in their names without prior written
*    permission of the Apache Group.
*
* THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
* WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
* OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
* DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR
* ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
* USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
* ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
* OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
* OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
* SUCH DAMAGE.
* ====================================================================
*
* This software consists of voluntary contributions made by many
* individuals on behalf of the Apache Software Foundation.  For more
* information on the Apache Software Foundation, please see
* <http://www.apache.org/>.
*/
namespace NVelocity.Runtime.Parser.Node {
    using System;
    using Parser = NVelocity.Runtime.Parser.Parser;
    using Token = NVelocity.Runtime.Parser.Token;
    using MethodInvocationException = NVelocity.Exception.MethodInvocationException;
    using ParseErrorException = NVelocity.Exception.ParseErrorException;
    using ResourceNotFoundException = NVelocity.Exception.ResourceNotFoundException;
    using InternalContextAdapter = NVelocity.Context.InternalContextAdapter;

    /// <summary>  All AST nodes must implement this interface.  It provides basic
    /// machinery for constructing the parent and child relationships
    /// between nodes.
    /// </summary>

    public interface INode {
	Token FirstToken {
	    get
		;

	    }
	    Token LastToken {
		get
		    ;

		}
		int Type {
		    get
			;

		    }
		    int Info {
			get
			    ;

			    set
				;

			    }
			    int Line {
				get
				    ;

				}
				int Column {
				    get
					;

				    }
				    /// <summary>  This method is called after the node has been made the current
				    /// node.  It indicates that child nodes can now be added to it.
				    /// </summary>
				    void  jjtOpen();
	///
	/// <summary>  This method is called after all the child nodes have been
	/// added.
	/// </summary>
	void  jjtClose();
	///
	/// <summary>  This pair of methods are used to inform the node of its
	/// parent.
	/// </summary>
	void  jjtSetParent(INode n);
	INode jjtGetParent();
	///
	/// <summary>  This method tells the node to add its argument to the node's
	/// list of children.
	/// </summary>
	void  jjtAddChild(INode n, int i);
	///
	/// <summary>  This method returns a child node.  The children are numbered
	/// from zero, left to right.
	/// </summary>
	INode jjtGetChild(int i);
	/// <summary>Return the number of children the node has.
	/// </summary>
	int jjtGetNumChildren();
	/// <summary>Accept the visitor. *
	/// </summary>
	System.Object jjtAccept(ParserVisitor visitor, System.Object data);
	System.Object childrenAccept(ParserVisitor visitor, System.Object data);
	// added
	System.Object init(InternalContextAdapter context, System.Object data);
	bool evaluate(InternalContextAdapter context);
	System.Object value_Renamed(InternalContextAdapter context);
	bool render(InternalContextAdapter context, System.IO.TextWriter writer);
	System.Object execute(System.Object o, InternalContextAdapter context);
	System.String literal();
	void  setInvalid();
	bool isInvalid();
    }
}
