namespace NVelocity.Runtime.Parser
{
	using System;
	using System.IO;

	/// <summary>  NOTE : This class was originally an ASCII_CharStream autogenerated
	/// by Javacc.  It was then modified via changing class name with appropriate
	/// fixes for CTORS, and mods to readChar().
	///
	/// This is safe because we *always* use Reader with this class, and never a
	/// InputStream.  This guarantees that we have a correct stream of 16-bit
	/// chars - all encoding transformations have been done elsewhere, so we
	/// believe that there is no risk in doing this.  Time will tell :)
	/// </summary>
	/// <summary> An implementation of interface CharStream, where the stream is assumed to
	/// contain only ASCII characters (without unicode processing).
	/// </summary>
	public sealed class VelocityCharStream : ICharStream
	{
		public const bool staticFlag = false;
		internal int bufferSize;
		internal int available;
		internal int tokenBegin;
		public int bufferPosition = -1;
		private int[] bufline;
		private int[] bufcolumn;

		private int column = 0;
		private int line = 1;

		private bool prevCharIsCR = false;
		private bool prevCharIsLF = false;

		private TextReader inputStream;

		private char[] buffer;
		private int maxNextCharInd = 0;
		private int inBuf = 0;
		private char currentCharacter;
		private bool currentCharacterAvailable = false;

		public VelocityCharStream(TextReader dstream,
								  int startline, int startcolumn, int buffersize)
		{
			inputStream = dstream;
			line = startline;
			column = startcolumn - 1;

			available = bufferSize = buffersize;
			buffer = new char[buffersize];
			bufline = new int[buffersize];
			bufcolumn = new int[buffersize];
		}

		public VelocityCharStream(TextReader dstream, int startline, int startcolumn)
			: this(dstream, startline, startcolumn, 4096)
		{
		}

		public void ReInit(TextReader dstream, int startline, int startcolumn, int buffersize)
		{
			inputStream = dstream;
			line = startline;
			column = startcolumn - 1;

			if (buffer == null || buffersize != buffer.Length)
			{
				available = bufferSize = buffersize;
				buffer = new char[buffersize];
				bufline = new int[buffersize];
				bufcolumn = new int[buffersize];
			}
			prevCharIsLF = prevCharIsCR = false;
			tokenBegin = inBuf = maxNextCharInd = 0;
			bufferPosition = -1;
		}

		public void ReInit(TextReader dstream, int startline, int startcolumn)
		{
			ReInit(dstream, startline, startcolumn, 4096);
		}

		public String GetImage()
		{
			if (bufferPosition >= tokenBegin)
			{
				Int32 len = (bufferPosition - tokenBegin + 1) > buffer.Length ? buffer.Length : (bufferPosition - tokenBegin + 1);
				//return new String(buffer, tokenBegin, bufferPosition - tokenBegin + 1);
				return new String(buffer, tokenBegin, len);
			}
			else
			{
				return new String(buffer, tokenBegin, bufferSize - tokenBegin) + new String(buffer, 0, bufferPosition + 1);
			}
		}

		public char[] GetSuffix(int len)
		{
			char[] ret = new char[len];

			if ((bufferPosition + 1) >= len)
				Array.Copy(buffer, bufferPosition - len + 1, ret, 0, len);
			else
			{
				Array.Copy(buffer, bufferSize - (len - bufferPosition - 1), ret, 0, len - bufferPosition - 1);
				Array.Copy(buffer, 0, ret, len - bufferPosition - 1, bufferPosition + 1);
			}

			return ret;
		}

		public void Done()
		{
			buffer = null;
			bufline = null;
			bufcolumn = null;
		}

		/// <summary> Method to adjust line and column numbers for the start of a token.<br/>
		/// </summary>
		public void AdjustBeginLineColumn(int newLine, int newCol)
		{
			int start = tokenBegin;
			int len;

			if (bufferPosition >= tokenBegin)
			{
				len = bufferPosition - tokenBegin + inBuf + 1;
			}
			else
			{
				len = bufferSize - tokenBegin + bufferPosition + 1 + inBuf;
			}

			int i = 0, j = 0, k = 0;
			int nextColDiff = 0, columnDiff = 0;

			while (i < len && bufline[j = start % bufferSize] == bufline[k = ++start % bufferSize])
			{
				bufline[j] = newLine;
				nextColDiff = columnDiff + bufcolumn[k] - bufcolumn[j];
				bufcolumn[j] = newCol + columnDiff;
				columnDiff = nextColDiff;
				i++;
			}

			if (i < len)
			{
				bufline[j] = newLine++;
				bufcolumn[j] = newCol + columnDiff;

				while (i++ < len)
				{
					if (bufline[j = start % bufferSize] != bufline[++start % bufferSize])
						bufline[j] = newLine++;
					else
						bufline[j] = newLine;
				}
			}

			line = bufline[j];
			column = bufcolumn[j];
		}

		public int Column
		{
			get { return bufcolumn[bufferPosition]; }
		}

		public int Line
		{
			get { return bufline[bufferPosition]; }
		}

		public int EndColumn
		{
			get { return bufcolumn[bufferPosition]; }
		}

		public int EndLine
		{
			get { return bufline[bufferPosition]; }
		}

		public int BeginColumn
		{
			get { return bufcolumn[tokenBegin]; }
		}

		public int BeginLine
		{
			get { return bufline[tokenBegin]; }
		}

		public char CurrentCharacter
		{
			get
			{
				if (!currentCharacterAvailable)
				{
					throw new InvalidOperationException("CurrentCharacter not available");
				}
				return currentCharacter;
			}
		}

		public bool CurrentCharacterAvailable
		{
			get
			{
				return currentCharacterAvailable;
			}
		}


		private void ExpandBuff(bool wrapAround)
		{
			char[] newbuffer = new char[bufferSize + 2048];
			int[] newbufline = new int[bufferSize + 2048];
			int[] newbufcolumn = new int[bufferSize + 2048];

			try
			{
				if (wrapAround)
				{
					Array.Copy(buffer, tokenBegin, newbuffer, 0, bufferSize - tokenBegin);
					Array.Copy(buffer, 0, newbuffer, bufferSize - tokenBegin, bufferPosition);
					buffer = newbuffer;

					Array.Copy(bufline, tokenBegin, newbufline, 0, bufferSize - tokenBegin);
					Array.Copy(bufline, 0, newbufline, bufferSize - tokenBegin, bufferPosition);
					bufline = newbufline;

					Array.Copy(bufcolumn, tokenBegin, newbufcolumn, 0, bufferSize - tokenBegin);
					Array.Copy(bufcolumn, 0, newbufcolumn, bufferSize - tokenBegin, bufferPosition);
					bufcolumn = newbufcolumn;

					maxNextCharInd = (bufferPosition += (bufferSize - tokenBegin));
				}
				else
				{
					Array.Copy(buffer, tokenBegin, newbuffer, 0, bufferSize - tokenBegin);
					buffer = newbuffer;

					Array.Copy(bufline, tokenBegin, newbufline, 0, bufferSize - tokenBegin);
					bufline = newbufline;

					Array.Copy(bufcolumn, tokenBegin, newbufcolumn, 0, bufferSize - tokenBegin);
					bufcolumn = newbufcolumn;

					maxNextCharInd = (bufferPosition -= tokenBegin);
				}
			}
			catch (Exception t)
			{
				throw new ApplicationException(t.Message);
			}

			bufferSize += 2048;
			available = bufferSize;
			tokenBegin = 0;
		}

		private bool FillBuff()
		{
			if (maxNextCharInd == available)
			{
				if (available == bufferSize)
				{
					if (tokenBegin > 2048)
					{
						bufferPosition = maxNextCharInd = 0;
						available = tokenBegin;
					}
					else if (tokenBegin < 0)
					{
						bufferPosition = maxNextCharInd = 0;
					}
					else
					{
						ExpandBuff(false);
					}
				}
				else if (available > tokenBegin)
				{
					available = bufferSize;
				}
				else if ((tokenBegin - available) < 2048)
				{
					ExpandBuff(true);
				}
				else
				{
					available = tokenBegin;
				}
			}

			try
			{
				int canRead = inputStream.Read(buffer, maxNextCharInd, available - maxNextCharInd);

				if (canRead <= 0)
				{
					inputStream.Close();
					return EndRead();
				}
				else
				{
					maxNextCharInd += canRead;
					return true;
				}
			}
			catch (Exception)
			{
				return EndRead();
			}
		}


		private bool EndRead()
		{
			--bufferPosition;
			Backup(0);
			if (tokenBegin == -1)
			{
				tokenBegin = bufferPosition;
			}
			return false;
		}


		public bool BeginToken()
		{
			tokenBegin = -1;
			bool success = ReadChar();
			if (success)
			{
				tokenBegin = bufferPosition;
			}

			return success;
		}

		private void UpdateLineColumn()
		{
			column++;

			if (prevCharIsLF)
			{
				prevCharIsLF = false;
				line += (column = 1);
			}
			else if (prevCharIsCR)
			{
				prevCharIsCR = false;
				if (currentCharacter == '\n')
				{
					prevCharIsLF = true;
				}
				else
					line += (column = 1);
			}

			switch (currentCharacter)
			{
				case '\r':
					prevCharIsCR = true;
					break;

				case '\n':
					prevCharIsLF = true;
					break;

				case '\t':
					column--;
					column += (8 - (column & 7));
					break;

				default:
					break;
			}

			bufline[bufferPosition] = line;
			bufcolumn[bufferPosition] = column;
		}


		public bool ReadChar()
		{
			if (inBuf > 0)
			{
				--inBuf;

				/*
				*  was : return (char)((char)0xff & buffer[(bufferPosition == bufferSize - 1) ? (bufferPosition = 0) : ++bufferPosition]);
				*/
				currentCharacterAvailable = true;
				currentCharacter = buffer[(bufferPosition == bufferSize - 1) ? (bufferPosition = 0) : ++bufferPosition];
				return true;
			}

			if (++bufferPosition >= maxNextCharInd)
			{
				if (!FillBuff())
				{
					currentCharacterAvailable = false;
					currentCharacter = default(Char);
					return false;
				}
			}

			/*
			*  was : char c = (char)((char)0xff & buffer[bufferPosition]);
			*/
			currentCharacterAvailable = true;
			currentCharacter = buffer[bufferPosition];

			UpdateLineColumn();
			return true;
		}

		public void Backup(int amount)
		{
			inBuf += amount;
			if ((bufferPosition -= amount) < 0)
			{
				bufferPosition += bufferSize;
			}
		}
	}
}
