// Copyright 2004-2007 Castle Project - http://www.castleproject.org/
// 
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
// 
//     http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

namespace Castle.MonoRail.Framework
{
	using System.Collections;
	using System.Collections.Specialized;

	/// <summary>
	/// THe UrlBuilder service centralizes the url generation used by the whole 
	/// framework including redirect urls, urls generated by helpers and so on. 
	/// It offers a central place to change MonoRail behavior on how to deal with urls. 
	/// </summary>
	public interface IUrlBuilder
	{
		/// <summary>
		/// Builds the URL using the current url as contextual information and a parameter dictionary.
		/// <para>
		/// Common parameters includes area, controller and action. 
		/// </para>
		/// </summary>
		/// <param name="current">The current Url information.</param>
		/// <param name="parameters">The parameters.</param>
		/// <returns></returns>
		string BuildUrl(UrlInfo current, IDictionary parameters);

		/// <summary>
		/// Builds an URL using the controller name and action name.
		/// </summary>
		/// <param name="current">The current Url information.</param>
		/// <param name="controller">The controller.</param>
		/// <param name="action">The action.</param>
		/// <returns></returns>
		string BuildUrl(UrlInfo current, string controller, string action);

		/// <summary>
		/// Builds an URL using the controller name, action name, and a querystring dictionary.
		/// </summary>
		/// <param name="current">The current Url information.</param>
		/// <param name="controller">The controller.</param>
		/// <param name="action">The action.</param>
		/// <param name="queryStringParams">The query string params.</param>
		/// <returns></returns>
		string BuildUrl(UrlInfo current, string controller, string action, IDictionary queryStringParams);

		/// <summary>
		/// Builds an URL using the controller name, action name, and a querystring name value collection.
		/// </summary>
		/// <param name="current">The current Url information.</param>
		/// <param name="controller">The controller.</param>
		/// <param name="action">The action.</param>
		/// <param name="queryStringParams">The query string params.</param>
		/// <returns></returns>
		string BuildUrl(UrlInfo current, string controller, string action, NameValueCollection queryStringParams);

		/// <summary>
		/// Builds an URL using the area name, controller name and action name.
		/// </summary>
		/// <param name="current">The current Url information.</param>
		/// <param name="area">The area.</param>
		/// <param name="controller">The controller.</param>
		/// <param name="action">The action.</param>
		/// <returns></returns>
		string BuildUrl(UrlInfo current, string area, string controller, string action);

		/// <summary>
		/// Builds an URL using the area name, controller name, action name, and a querystring dictionary.
		/// </summary>
		/// <param name="current">The current Url information.</param>
		/// <param name="area">The area.</param>
		/// <param name="controller">The controller.</param>
		/// <param name="action">The action.</param>
		/// <param name="queryStringParams">The query string params.</param>
		/// <returns></returns>
		string BuildUrl(UrlInfo current, string area, string controller, string action, IDictionary queryStringParams);

		/// <summary>
		/// Builds an URL using the area name, controller name, action name, and a querystring name value collection.
		/// </summary>
		/// <param name="current">The current Url information.</param>
		/// <param name="area">The area.</param>
		/// <param name="controller">The controller.</param>
		/// <param name="action">The action.</param>
		/// <param name="queryStringParams">The query string params.</param>
		/// <returns></returns>
		string BuildUrl(UrlInfo current, string area, string controller, string action, NameValueCollection queryStringParams);

		/// <summary>
		/// Pendent.
		/// </summary>
		/// <param name="current">The current.</param>
		/// <param name="routeName">Name of the route.</param>
		/// <returns></returns>
		string BuildRouteUrl(UrlInfo current, string routeName);
	}
}
