namespace NVelocity.Runtime.Parser.Node
{
    /* Generated By:JJTree: Do not edit this line. ASTIntegerRange.java */
    /*
    * The Apache Software License, Version 1.1
    *
    * Copyright (c) 2000-2001 The Apache Software Foundation.  All rights
    * reserved.
    *
    * Redistribution and use in source and binary forms, with or without
    * modification, are permitted provided that the following conditions
    * are met:
    *
    * 1. Redistributions of source code must retain the above copyright
    *    notice, this list of conditions and the following disclaimer.
    *
    * 2. Redistributions in binary form must reproduce the above copyright
    *    notice, this list of conditions and the following disclaimer in
    *    the documentation and/or other materials provided with the
    *    distribution.
    *
    * 3. The end-user documentation included with the redistribution, if
    *    any, must include the following acknowlegement:
    *       "This product includes software developed by the
    *        Apache Software Foundation (http://www.apache.org/)."
    *    Alternately, this acknowlegement may appear in the software itself,
    *    if and wherever such third-party acknowlegements normally appear.
    *
    * 4. The names "The Jakarta Project", "Velocity", and "Apache Software
    *    Foundation" must not be used to endorse or promote products derived
    *    from this software without prior written permission. For written
    *    permission, please contact apache@apache.org.
    *
    * 5. Products derived from this software may not be called "Apache"
    *    nor may "Apache" appear in their names without prior written
    *    permission of the Apache Group.
    *
    * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
    * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
    * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
    * DISCLAIMED.  IN NO EVENT SHALL THE APACHE SOFTWARE FOUNDATION OR
    * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
    * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
    * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
    * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
    * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
    * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
    * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
    * SUCH DAMAGE.
    * ====================================================================
    *
    * This software consists of voluntary contributions made by many
    * individuals on behalf of the Apache Software Foundation.  For more
    * information on the Apache Software Foundation, please see
    * <http://www.apache.org/>.
    */
    /// <summary> handles the range 'operator'  [ n .. m ]
    ///
    /// Please look at the Parser.jjt file which is
    /// what controls the generation of this class.
    /// *
    /// </summary>
    /// <author> <a href="mailto:geirm@optonline.net">Geir Magnusson Jr.</a>
    /// </author>
    /// <version> $Id: ASTIntegerRange.cs,v 1.3 2003/10/27 13:54:10 corts Exp $
    /// </version>
    using System;
    using System.Collections;
    using Parser = NVelocity.Runtime.Parser.Parser;
    using MethodInvocationException = NVelocity.Exception.MethodInvocationException;
    using InternalContextAdapter = NVelocity.Context.InternalContextAdapter;

    public class ASTIntegerRange:SimpleNode {

	public ASTIntegerRange(int id):base(id) {}

	public ASTIntegerRange(Parser p, int id):base(p, id) {}

	/// <summary>Accept the visitor. *
	/// </summary>
	public override System.Object jjtAccept(ParserVisitor visitor, System.Object data) {
	    return visitor.visit(this, data);
	}

	/// <summary>  does the real work.  Creates an Vector of Integers with the
	/// right value range
	/// *
	/// </summary>
	/// <param name="context"> app context used if Left or Right of .. is a ref
	/// </param>
	/// <returns>Object array of Integers
	///
	/// </returns>
	public override System.Object value_Renamed(InternalContextAdapter context) {
	    /*
	    *  get the two range ends
	    */

	    System.Object left = jjtGetChild(0).value_Renamed(context);
	    System.Object right = jjtGetChild(1).value_Renamed(context);

	    /*
	    *  if either is null, lets log and bail
	    */

	    if (left == null || right == null) {
		rsvc.error((left == null?"Left":"Right") + " side of range operator [n..m] has null value." + " Operation not possible. " + context.CurrentTemplateName + " [line " + Line + ", column " + Column + "]");
		return null;
	    }

	    /*
	    *  if not an Integer, not much we can do either
	    */

	    if (!(left is System.Int32) || !(right is System.Int32)) {
		rsvc.error((!(left is System.Int32)?"Left":"Right") + " side of range operator is not a valid type. " + "Currently only integers (1,2,3...) and Integer type is supported. " + context.CurrentTemplateName + " [line " + Line + ", column " + Column + "]");

		return null;
	    }


	    /*
	    *  get the two integer values of the ends of the range
	    */

	    int l = ((System.Int32) left);
	    int r = ((System.Int32) right);

	    /*
	    *  find out how many there are
	    */

	    int num = System.Math.Abs(l - r);
	    num += 1;

	    /*
	    *  see if your increment is Pos or Neg
	    */

	    int delta = (l >= r)?- 1:1;

	    /*
	    *  make the vector and fill it
	    */

	    ArrayList foo = new ArrayList();
	    int val = l;

	    for (int i = 0; i < num; i++) {
		foo.Add(val);
		val += delta;
	    }

	    return foo;
	}
    }
}
