//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4918
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle.Components.Validator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal partial class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Castle.Components.Validator.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection must not be empty.
        /// </summary>
        internal static string collection_not_empty {
            get {
                return ResourceManager.GetString("collection_not_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value does not appear to be a valid credit card number, or is of an unsupported type..
        /// </summary>
        internal static string credit_card_invalid {
            get {
                return ResourceManager.GetString("credit_card_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid date.
        /// </summary>
        internal static string date_invalid {
            get {
                return ResourceManager.GetString("date_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid decimal in this field.
        /// </summary>
        internal static string decimal_invalid {
            get {
                return ResourceManager.GetString("decimal_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid double in this field.
        /// </summary>
        internal static string double_invalid {
            get {
                return ResourceManager.GetString("double_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address. For example fred@domain.com.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be {0} characters long.
        /// </summary>
        internal static string exactlength {
            get {
                return ResourceManager.GetString("exactlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field has an invalid content.
        /// </summary>
        internal static string generic_invalid {
            get {
                return ResourceManager.GetString("generic_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field value must be greater than the other field value..
        /// </summary>
        internal static string greater_than_invalid {
            get {
                return ResourceManager.GetString("greater_than_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the values should not be empty.
        /// </summary>
        internal static string group_not_empty_invalid {
            get {
                return ResourceManager.GetString("group_not_empty_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid GUID (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
        /// </summary>
        internal static string guid {
            get {
                return ResourceManager.GetString("guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid integer in this field.
        /// </summary>
        internal static string integer_invalid {
            get {
                return ResourceManager.GetString("integer_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid IP address..
        /// </summary>
        internal static string ipaddress {
            get {
                return ResourceManager.GetString("ipaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a required field.
        /// </summary>
        internal static string isrequired {
            get {
                return ResourceManager.GetString("isrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be between {0} and {1} characters long.
        /// </summary>
        internal static string length_invalidrange {
            get {
                return ResourceManager.GetString("length_invalidrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be less than {0} characters long.
        /// </summary>
        internal static string length_toolong {
            get {
                return ResourceManager.GetString("length_toolong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be at least {0} characters long.
        /// </summary>
        internal static string length_tooshort {
            get {
                return ResourceManager.GetString("length_tooshort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field value must be lesser than the other field value..
        /// </summary>
        internal static string lesser_than_invalid {
            get {
                return ResourceManager.GetString("lesser_than_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields should not match.
        /// </summary>
        internal static string not_same_as_invalid {
            get {
                return ResourceManager.GetString("not_same_as_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must not equals &apos;{0}&apos;.
        /// </summary>
        internal static string not_same_value_invalid {
            get {
                return ResourceManager.GetString("not_same_value_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be between {0} and {1}.
        /// </summary>
        internal static string range_invalid {
            get {
                return ResourceManager.GetString("range_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be less than or equal to {0}.
        /// </summary>
        internal static string range_toohigh {
            get {
                return ResourceManager.GetString("range_toohigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be between {0} and {1}.
        /// </summary>
        internal static string range_toohighorlow {
            get {
                return ResourceManager.GetString("range_toohighorlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be greater than or equal to {0}.
        /// </summary>
        internal static string range_toolow {
            get {
                return ResourceManager.GetString("range_toolow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields do not match.
        /// </summary>
        internal static string same_as_invalid {
            get {
                return ResourceManager.GetString("same_as_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must be within a given set of values..
        /// </summary>
        internal static string set_invalid {
            get {
                return ResourceManager.GetString("set_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value is invalid (not a valid single).
        /// </summary>
        internal static string single_invalid {
            get {
                return ResourceManager.GetString("single_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field value is invalid (not a valid time).
        /// </summary>
        internal static string time_invalid {
            get {
                return ResourceManager.GetString("time_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid time-span (ddd.hh:mm:ss.xxx).
        /// </summary>
        internal static string timespan {
            get {
                return ResourceManager.GetString("timespan", resourceCulture);
            }
        }
    }
}
