//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Castle.Facilities.WcfIntegration.Demo.UsingWindsorSvc
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Castle.Facilities.WcfIntegration.Demo.UsingWindsorSvc.IAmUsingWindsor")]
    public interface IAmUsingWindsor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAmUsingWindsor/GetValueFromWindsorConfig", ReplyAction="http://tempuri.org/IAmUsingWindsor/GetValueFromWindsorConfigResponse")]
        int GetValueFromWindsorConfig();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IAmUsingWindsorChannel : Castle.Facilities.WcfIntegration.Demo.UsingWindsorSvc.IAmUsingWindsor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AmUsingWindsorClient : System.ServiceModel.ClientBase<Castle.Facilities.WcfIntegration.Demo.UsingWindsorSvc.IAmUsingWindsor>, Castle.Facilities.WcfIntegration.Demo.UsingWindsorSvc.IAmUsingWindsor
    {
        
        public AmUsingWindsorClient()
        {
        }
        
        public AmUsingWindsorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AmUsingWindsorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AmUsingWindsorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AmUsingWindsorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public int GetValueFromWindsorConfig()
        {
            return base.Channel.GetValueFromWindsorConfig();
        }
    }
}
