// $ANTLR 2.7.5 (20050128): "lang4.g" -> "RookLexer.cs"$

	// using CommonAST					= antlr.CommonAST; 
	using System.Text;
	using System.Collections;
	using Castle.Rook.Compiler.AST;
	using Castle.Rook.Compiler.Services;

namespace Castle.Rook.Compiler.Parser
{
	public class RookTokenTypes
	{
		public const int EOF = 1;
		public const int NULL_TREE_LOOKAHEAD = 3;
		public const int CLASS = 4;
		public const int DO = 5;
		public const int END = 6;
		public const int DEF = 7;
		public const int OPERATOR = 8;
		public const int BEGIN = 9;
		public const int WHILE = 10;
		public const int TYPE = 11;
		public const int METHOD_CALL = 12;
		public const int SUPER_CTOR_CALL = 13;
		public const int POST_INC = 14;
		public const int POST_DEC = 15;
		public const int EXPR = 16;
		public const int ELIST = 17;
		public const int INDEX_OP = 18;
		public const int UNARY_MINUS = 19;
		public const int UNARY_PLUS = 20;
		public const int TYPECAST = 21;
		public const int ARRAY_DECLARATOR = 22;
		public const int NUM_INT = 23;
		public const int NUM_DOUBLE = 24;
		public const int NUM_FLOAT = 25;
		public const int NUM_LONG = 26;
		public const int STATEMENT_END = 27;
		public const int SEMI = 28;
		public const int LITERAL_namespace = 29;
		public const int UNTIL = 30;
		public const int LITERAL_for = 31;
		public const int LITERAL_in = 32;
		public const int LITERAL_if = 33;
		public const int LITERAL_then = 34;
		public const int LITERAL_elsif = 35;
		public const int LITERAL_else = 36;
		public const int LITERAL_unless = 37;
		public const int LITERAL_redo = 38;
		public const int LITERAL_break = 39;
		public const int LITERAL_next = 40;
		public const int LITERAL_retry = 41;
		public const int LITERAL_public = 42;
		public const int COLON = 43;
		public const int LITERAL_private = 44;
		public const int LITERAL_protected = 45;
		public const int LITERAL_internal = 46;
		public const int COMMA = 47;
		public const int ASSIGN = 48;
		public const int IDENT = 49;
		public const int LTHAN = 50;
		public const int SL = 51;
		public const int LPAREN = 52;
		public const int RPAREN = 53;
		public const int STAR = 54;
		public const int BAND = 55;
		public const int PLUS_ASSIGN = 56;
		public const int MINUS_ASSIGN = 57;
		public const int STAR_ASSIGN = 58;
		public const int DIV_ASSIGN = 59;
		public const int MOD_ASSIGN = 60;
		public const int BAND_ASSIGN = 61;
		public const int BOR_ASSIGN = 62;
		public const int BXOR_ASSIGN = 63;
		public const int LITERAL_until = 64;
		public const int STATICIDENT = 65;
		public const int INSTIDENT = 66;
		public const int DOT = 67;
		public const int SYMBOL = 68;
		public const int LITERAL_lambda = 69;
		public const int LCURLY = 70;
		public const int RCURLY = 71;
		public const int LITERAL_raise = 72;
		public const int LITERAL_yield = 73;
		public const int BOR = 74;
		public const int LITERAL_or = 75;
		public const int LITERAL_and = 76;
		public const int LITERAL_not = 77;
		public const int LNOT = 78;
		public const int GT = 79;
		public const int EQUAL = 80;
		public const int GE = 81;
		public const int LE = 82;
		public const int NOT_EQUAL = 83;
		public const int BXOR = 84;
		public const int PLUS = 85;
		public const int MINUS = 86;
		public const int SLASH = 87;
		public const int PERCENT = 88;
		public const int BNOT = 89;
		public const int LBRACK = 90;
		public const int RBRACK = 91;
		public const int STRING_LITERAL = 92;
		public const int CHAR_LITERAL = 93;
		public const int DOTDOT = 94;
		public const int DOTDOTDOT = 95;
		public const int MAPASSIGN = 96;
		public const int QUESTION = 97;
		public const int DIV = 98;
		public const int INC = 99;
		public const int DEC = 100;
		public const int MOD = 101;
		public const int SR = 102;
		public const int SR_ASSIGN = 103;
		public const int BSR = 104;
		public const int BSR_ASSIGN = 105;
		public const int SL_ASSIGN = 106;
		public const int LOR = 107;
		public const int LAND = 108;
		public const int NEWLINE = 109;
		public const int SL_NEWLINE = 110;
		public const int SL_COMMENT = 111;
		public const int WS = 112;
		public const int ESC = 113;
		public const int HEX_DIGIT = 114;
		public const int VOCAB = 115;
		public const int NUMBER = 116;
		public const int Int = 117;
		public const int NonZeroDigit = 118;
		public const int FloatTrailer = 119;
		public const int Exponent = 120;
		public const int CONTINUED_LINE = 121;
		
	}
}
