using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("CastleGen for Microsoft .NET Framework 2.0")]
[assembly: AssemblyDescriptionAttribute("Castle Project\'s Command Line interface for the NewGenerator")]
[assembly: AssemblyCompanyAttribute("Castle Project")]
[assembly: AssemblyProductAttribute("CastleGen")]
[assembly: AssemblyCopyrightAttribute("Castle Project, original author or authors")]
[assembly: AssemblyVersionAttribute("0.0.1.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.0.1.0")]
[assembly: AssemblyDelaySignAttribute(false)]

